# Use postgres/example user/password credentials
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: turtlerock
      POSTGRES_USER: cybersim
      POSTGRES_DB: cybersim
    ports:
      - 5432:5432
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cybersim"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
